name: dost_mobile
description: "Dost AI - Türkçe AI Asistan"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  pdf: ^3.1.34
  path_provider: ^2.1.1
  printing: ^5.11.1
  flutter_tts: ^4.0.2 
  flutter:
    sdk: flutter
  
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: any
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.1
  easy_localization: ^3.0.7  # YENİ - Çoklu dil desteği

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:  # YENİ - Translation dosyalarını ekle
    - assets/translations/